App_auth/urls.py
from django.urls import path
from . import views


app_name = 'App_auth'

urlpatterns = [
    path('admin-signup/', views.admin_signup, name='admin-signup'),
    path('trainer-signup/', views.trainer_signup, name='trainer-signup'),
    path('member-signup/', views.member_signup, name='member-signup'),
    path('login/', views.login_system, name='login'),
    path('log-out/', views.logout_system, name='log-out'),

]

App_main/urls.py
from django.urls import path
from . import views

app_name = 'App_main'

urlpatterns = [
    path('', views.index, name='index'),
    # admin
    path('member-dashboard', views.member_dashboard, name='member-dashboard'),
    path('admin-dashboard', views.admin_dashboard, name='admin-dashboard'),
    path('trainer-dashboard', views.trainer_dashboard, name='trainer-dashboard'),
    path('assign-trainers', views.assign_trainers, name='assign-trainers'),
    path('assign-trainer/<int:pk>/', views.assign_trainer, name='assign-trainer'),
    path('total-members', views.total_members, name='total-members'),
    path('admin-health-stat', views.admin_health_stat, name='admin-health-stat'),
    path('admin-health-each/<int:pk>/', views.admin_health_each, name='admin-health-each'),
    # trainer
    path('my-trainees', views.my_trainees, name='my-trainees'),
    path('workout-plan/<int:pk>/', views.workout_plan, name='workout-plan'),
    path('dietchart/<int:pk>/', views.diet_chart, name='dietchart'),
    path('trainer-health/', views.trainer_health, name='trainer-health'),
    path('health-stat-trainer/', views.health_stat_trainer, name='health-stat-trainer'),
    path('trainer-targets/', views.trainer_targets, name='trainer-targets'),
    path('target-stat/<int:pk>/', views.target_stat, name='target-stat'),
    path('trainer-inbox/<int:pk>/', views.trainer_inbox, name='trainer-inbox'),
    path('trainer-chatbox/', views.trainer_chatbox, name='trainer-chatbox'),
    path('trainer-diet-list/', views.trainer_diet_list, name='trainer-diet-list'),
    # member
    path('member-health/', views.member_health, name='member-health'),
    path('my-trainer/', views.my_trainer, name='my-trainer'),
    path('my-diet/', views.my_diet_chart, name='my-diet'),
    path('my-workout/', views.my_workout, name='my-workout'),
    path('health-stat/', views.health_stat, name='health-stat'),
    path('inbox/', views.member_inbox, name='inbox'),
]

GWTS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('App_auth.urls')),
    path('', include('App_main.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_main/models.py
from django.contrib.auth.models import User
from django.db import models
from App_auth.models import TrainerModel, MemberModel


# Create your models here.


class DietChartModel(models.Model):
    trainer = models.ForeignKey(TrainerModel, on_delete=models.CASCADE, related_name='chart_provider')
    trainee = models.ForeignKey(MemberModel, on_delete=models.CASCADE, related_name='chart_follower')
    sunday_breakfast = models.CharField(max_length=500)
    sunday_lunch = models.CharField(max_length=500)
    sunday_dinner = models.CharField(max_length=500)
    sunday_snacks = models.CharField(max_length=500)

    monday_breakfast = models.CharField(max_length=500)
    monday_lunch = models.CharField(max_length=500)
    monday_dinner = models.CharField(max_length=500)
    monday_snacks = models.CharField(max_length=500)

    tuesday_breakfast = models.CharField(max_length=500)
    tuesday_lunch = models.CharField(max_length=500)
    tuesday_dinner = models.CharField(max_length=500)
    tuesday_snacks = models.CharField(max_length=500)

    wednesday_breakfast = models.CharField(max_length=500)
    wednesday_lunch = models.CharField(max_length=500)
    wednesday_dinner = models.CharField(max_length=500)
    wednesday_snacks = models.CharField(max_length=500)

    thursday_breakfast = models.CharField(max_length=500)
    thursday_lunch = models.CharField(max_length=500)
    thursday_dinner = models.CharField(max_length=500)
    thursday_snacks = models.CharField(max_length=500)

    friday_breakfast = models.CharField(max_length=500)
    friday_lunch = models.CharField(max_length=500)
    friday_dinner = models.CharField(max_length=500)
    friday_snacks = models.CharField(max_length=500)

    saturday_breakfast = models.CharField(max_length=500)
    saturday_lunch = models.CharField(max_length=500)
    saturday_dinner = models.CharField(max_length=500)
    saturday_snacks = models.CharField(max_length=500)
    issued = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.issued} {self.trainer.user.first_name} {self.trainer.user.last_name}-{self.trainee.user.first_name} {self.trainee.user.last_name}"


class Workout(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class WorkoutPlanModel(models.Model):
    trainer = models.ForeignKey(TrainerModel, on_delete=models.CASCADE, related_name='plan_provider')
    trainee = models.ForeignKey(MemberModel, on_delete=models.CASCADE, related_name='plan_follower')
    sunday = models.ManyToManyField(Workout, related_name='sunday_plan')
    monday = models.ManyToManyField(Workout, related_name='monday_plan')
    tuesday = models.ManyToManyField(Workout, related_name='tuesday_plan')
    wednesday = models.ManyToManyField(Workout, related_name='wednesday_plan')
    thursday = models.ManyToManyField(Workout, related_name='thursday_plan')
    friday = models.ManyToManyField(Workout, related_name='friday_plan')
    saturday = models.ManyToManyField(Workout, related_name='saturday_plan')
    duration = models.PositiveIntegerField(default=0)
    created = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.created} {self.trainer.user.first_name} {self.trainer.user.last_name}-{self.trainee.user.first_name} {self.trainee.user.last_name}"


class BMIModel(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bmi_user')
    height = models.FloatField()
    weight = models.FloatField()
    age = models.IntegerField()
    sex = models.CharField(max_length=6)
    bmi = models.FloatField()
    weight_status = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.person.first_name} {self.person.last_name}'s BMI: {self.bmi}"


class MessageModel(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender_user')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver_user')
    receiver_seen = models.BooleanField(default=False)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender.first_name}-{self.receiver.first_name}"

App_main/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count, Min, Q
from django.shortcuts import render, get_object_or_404, reverse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.
from App_auth.forms import MemberUpdateForm
from App_auth.models import MemberModel, AdminModel, TrainerModel
from App_main.forms import WorkoutPlanModelForm, DietChartModelForm, BMIForm
from App_main.models import WorkoutPlanModel, DietChartModel, BMIModel, MessageModel


def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()


def is_trainer(user):
    return user.groups.filter(name='TRAINER').exists()


def is_member(user):
    return user.groups.filter(name='MEMBER').exists()


def index(request):
    return render(request, 'App_main/index.html')


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def member_dashboard(request):
    profile = MemberModel.objects.get(user=request.user)
    message = MessageModel.objects.filter(receiver=request.user, receiver_seen=False).count()
    content = {
        'profile': profile,
        'message': message
    }
    return render(request, 'App_main/member_dashboard.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def my_diet_chart(request):
    profile = MemberModel.objects.get(user=request.user)
    diet = DietChartModel.objects.filter(trainee=profile.id).order_by('-issued').first()
    content = {
        'diet': diet
    }
    return render(request, 'App_main/diet_chart.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def my_workout(request):
    profile = MemberModel.objects.get(user=request.user)
    plans = '$'
    try:
        plans = WorkoutPlanModel.objects.filter(trainee=profile).order_by('-created')
    except ObjectDoesNotExist:
        plans = '$'
    content = {
        'plans': plans
    }
    return render(request, 'App_main/my_workout.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def member_health(request):
    if request.method == 'POST':
        height = float(request.POST.get('height'))
        weight = float(request.POST.get('weight'))
        age = int(request.POST.get('age'))
        sex = request.POST.get('sex')

        bmi = weight / (height / 100 * height / 100)
        weight_status = ''
        if bmi < 18.5:
            weight_status = 'Underweight'
        elif bmi < 25:
            weight_status = 'Healthy'
        elif bmi < 30:
            weight_status = 'Overweight'
        else:
            weight_status = 'Obese'

        user = request.user
        bmi_model = BMIModel(person=user, height=height, weight=weight, age=age, sex=sex, bmi=bmi,
                             weight_status=weight_status)
        bmi_model.save()
        status = weight_status
    else:
        try:
            bmi_object = BMIModel.objects.filter(person=request.user).order_by('-created').first()
            status = bmi_object.weight_status
        except (BMIModel.DoesNotExist, AttributeError):
            status = 'Not Checked Yet'

    return render(request, 'App_main/member_health.html', {'status': status})


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def my_trainer(request):
    profile = MemberModel.objects.get(user=request.user)
    trainer = TrainerModel.objects.get(id=profile.my_trainer.id)
    content = {
        'profile': profile,
        'trainer': trainer
    }
    return render(request, 'App_main/my_trainer.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def health_stat(request):
    profile = MemberModel.objects.get(user=request.user)
    bmi_data = BMIModel.objects.filter(person=request.user).order_by('-created')[:12][::-1]
    content = {
        'profile': profile,
        'bmi_data': bmi_data
    }
    return render(request, 'App_main/health_stat.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_member)
def member_inbox(request):
    profile = MemberModel.objects.get(user=request.user)
    trainer = TrainerModel.objects.get(id=profile.my_trainer.id)
    messages = MessageModel.objects.filter(sender=request.user) | MessageModel.objects.filter(receiver=request.user)
    messages = messages.order_by('created')
    unseen = MessageModel.objects.filter(receiver=request.user, receiver_seen=False)
    for i in unseen:
        i.receiver_seen = True
        i.save()
    if request.method == 'POST':
        msg = request.POST.get('msg')
        msg_model = MessageModel(sender=request.user, receiver=trainer.user, message=msg)
        msg_model.save()
    content = {
        'messages': messages,
        'trainer': trainer
    }
    return render(request, 'App_main/inbox.html', context=content)


# ------------------------------------------------member end-------------------------------------------
# ------------------------------------------------admin start-------------------------------------------

@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def admin_dashboard(request):
    profile = AdminModel.objects.get(user=request.user)
    members = MemberModel.objects.all()
    content = {
        'profile': profile,
        'members': members.count(),
    }
    return render(request, 'App_main/admin_dashboard.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def assign_trainers(request):
    members = MemberModel.objects.filter(my_trainer=None)
    trainers = TrainerModel.objects.all()
    content = {
        'members': members,
        'trainers': trainers,
    }
    return render(request, 'App_main/assign_trainers.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def assign_trainer(request, pk):
    trainer_id = request.POST.get('trainer')
    trainer = TrainerModel.objects.get(id=trainer_id)
    member = MemberModel.objects.get(id=pk)
    member.my_trainer = trainer
    member.save()
    return HttpResponseRedirect(reverse('App_main:assign-trainers'))


@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def total_members(request):
    members = MemberModel.objects.all()
    content = {
        'members': members
    }
    return render(request, 'App_main/total_members.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def admin_health_stat(request):
    members = MemberModel.objects.all()
    content = {
        'members': members
    }
    return render(request, 'App_main/admin_health_stat.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_admin)
def admin_health_each(request, pk):
    member = MemberModel.objects.get(user_id=pk)
    bmi_data = BMIModel.objects.filter(person_id=pk).order_by('-created')[:12][::-1]
    plans = '$'
    try:
        plans = WorkoutPlanModel.objects.filter(trainee=member).order_by('-created').first()
    except ObjectDoesNotExist:
        plans = '$'
    charts = '$'
    try:
        charts = DietChartModel.objects.filter(trainee=member).order_by('-issued').first()
    except ObjectDoesNotExist:
        charts = '$'
    content = {
        'member': member,
        'bmi_data': bmi_data,
        'chart': charts,
        'plan': plans
    }
    return render(request, 'App_main/admin_health_each.html', context=content)


# ------------------------------------------------admin end-------------------------------------------
# ------------------------------------------------trainer start---------------------------------------

@login_required(login_url='App_auth:login')
@user_passes_test(is_trainer)
def trainer_dashboard(request):
    profile = TrainerModel.objects.get(user=request.user)
    members = MemberModel.objects.filter(my_trainer=profile)
    message = MessageModel.objects.filter(receiver=request.user, receiver_seen=False).count()
    content = {
        'profile': profile,
        'members': members.count(),
        'message': message
    }
    return render(request, 'App_main/trainer_dashboard.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_trainer)
def my_trainees(request):
    profile = TrainerModel.objects.get(user=request.user)
    members = MemberModel.objects.filter(my_trainer=profile)
    content = {
        'profile': profile,
        'members': members,
    }
    return render(request, 'App_main/my_trainees.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_trainer)
def workout_plan(request, pk):
    profile = TrainerModel.objects.get(user=request.user)
    member = MemberModel.objects.get(id=pk)
    plans = '$'
    try:
        plans = WorkoutPlanModel.objects.filter(trainer=profile, trainee=member).order_by('-created')
    except ObjectDoesNotExist:
        plans = '$'
    form = WorkoutPlanModelForm()
    if request.method == 'POST':
        form = WorkoutPlanModelForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                form.save(profile, member)
                return HttpResponseRedirect(reverse('App_main:my-trainees'))
    content = {
        'form': form,
        'plans': plans
    }
    return render(request, 'App_main/workoutplan.html', context=content)


@login_required(login_url='App_auth:login')
@user_passes_test(is_trainer)
def diet_chart(request, pk):
    profile = TrainerModel.objects.get(user=request.user)
    member = MemberModel.objects.get(id=pk)
    charts = '$'
    try:
        charts = DietChartModel.objects.filter(trainer=profile, trainee=member).order_by('-issued')
    except ObjectDoesNotExist:
        charts = '$'
    form = DietChartModelForm()
    if request.method == 'POST':

templates/App_main/assign_trainers.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GWTS | Assign Trainer</title>
</head>
<body>


<style>
    @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800;900&display=swap');

    * {
        font-family: 'Nunito';
        background-color: black;
        color: white;
    }

    #tableLandlord {
        font-size: 125%;
        white-space: nowrap;
        margin: 0;
        border: none;
        border-collapse: separate;
        border-spacing: 0;
        table-layout: fixed;
    }

    #tableLandlord td,
    #tableLandlord th {
        padding: 0.5rem 1rem;
    }

    #tableLandlord thead th {
        padding: 3px;
        position: sticky;
        top: 0;
        z-index: 1;
        width: 25vw;
        padding-left: 6px;
        padding-right: 6px;
    }

    #tableLandlord td {
        padding: 4px 5px;
        text-align: center;
    }

    #tableLandlord tbody tr:nth-child(odd) th,
    #tableLandlord tbody tr:nth-child(odd) td {
    }

    .submit {
        text-decoration: none;
        color: white;
        padding: 2px 5px;
        background-color: #f52f05;
        border: 1px solid #f52f05;
        border-radius: 30%;
    }

    .home {
        text-decoration: none;

        font-weight: bold;
        font-size: 18px;
        background-color: #f52f05;
        padding: 12px;
        border-radius: 10% 30% 50% 70%;
    }
</style>

<div class="container mx-auto py-5 text-center flex flex-col justify-center items-center">
    <a href="{% url 'App_main:admin-dashboard' %}" class="home"> GWTS </a>
    <h1 class="text-[1.2rem] sm:text-[1.4rem] pb-8" style="text-align: center; color: #f56040">
        Assign a Trainer
    </h1>
    <hr style="background-color: #f56040; border: 2px solid #f56040">

    <div class="w-full overflow-auto" tabindex="0" id="tableLandlord">
        <table class="overflow-scroll">
            <thead>
            <tr>
                <th style="border: 1px solid #f56040">Index</th>
                <th style="border: 1px solid #f56040">Member</th>
                <th style="border: 1px solid #f56040">Age</th>
                <th style="border: 1px solid #f56040">Gender</th>
                <th style="border: 1px solid #f56040">Joined</th>
                <th style="border: 1px solid #f56040">Trainer</th>
                <th style="border: 1px solid #f56040">Apply</th>
            </tr>
            </thead>
            <tbody>
            {% for member in members %}
                <tr style="text-align: center;">
                    <th style="border-bottom: 1px solid #f56040">{{ forloop.counter }}</th>
                    <th style="border-bottom: 1px solid #f56040">{{ member.user.first_name }} {{ member.user.last_name }}</th>
                    <td style="border-bottom: 1px solid #f56040">{{ member.age }}</td>
                    <td style="border-bottom: 1px solid #f56040">{{ member.gender }}</td>
                    <td style="border-bottom: 1px solid #f56040">{{ member.joining_date }}</td>
                    <form method="post"
                          action="{% url 'App_main:assign-trainer' pk=member.id %}">
                        {% csrf_token %}
                        <td style="border-bottom: 1px solid #f56040">
                            <select name="trainer">
                                {% for trainer in trainers %}
                                    <option value="{{ trainer.id }}">{{ trainer.user.first_name }} {{ trainer.user.last_name }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td style="border-bottom: 1px solid #f56040"><button
                                 type="submit"
                                class="submit">Apply</button></td>
                    </form>
                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>

</div>
</body>
</html>

templates/App_main/my_trainer.html
<!doctype html>
<html lang="en">
{% load crispy_forms_filters %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GWTS | Assign Trainer</title>
</head>
<body style="overflow-x: hidden">


<style>
    @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800;900&display=swap');

    * {
        font-family: 'Nunito';
        background-color: black;
        color: white;
    }


    .submit {
        justify-content: center !important;
        text-decoration: none;
        color: white;
        background-color: #f52f05;
        border: 1px solid #f52f05;
        height: 40px;
        width: 100%;
        float: right;
        font-size: 18px;

    }

    .add {
        text-decoration: none;
        color: white;
        background-color: #f52f05;
        border: 1px solid #f52f05;
        height: 100%;
        width: 100%;
        font-size: 18px;
    }

    .add:hover {
        background-color: #f5401a;
        color: white;
    }

    .home {
        text-decoration: none;

        font-weight: bold;
        font-size: 18px;
        background-color: #f52f05;
        padding: 12px;
        border-radius: 10% 30% 50% 70%;
    }

    hr {
        color: #f52f05;
    }

    .select-options-horizontal select {
        display: flex;
    }

    .select-options-horizontal option {
        flex: 1;
    }

    #id_duration {
        width: 100%;
        border: 3px solid white;
        margin-bottom: 15px;
        color: white;
    }

    input {
        border: 2px solid white;
        margin-bottom: 5px;
        width: 100% !important;
    }

    img {
        height: 400px;
        width: 300px;
        justify-content: center !important;
        margin: 5px;
    }

    h5, h6 {
        margin-left: 10px !important;
    }

</style>

<div class="">
    <a href="{% url 'App_main:member-dashboard' %}" style="text-decoration: none; color: white" class="home"> GWTS </a>
    <h1 class="text-[1.2rem] sm:text-[1.4rem] pb-8" style="text-align: center; color: #f56040">
        My Trainer
    </h1>
    <hr style="background-color: #f56040; border: 2px solid #f56040">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-3">
            <img src="{{ trainer.profile_picture.url }}" alt="">
        </div>
        <div class="col-lg-5">
            <hr style="background-color: #f56040; border: 2px solid #f56040">
            <hr style="background-color: #f56040; border: 2px solid #f56040">
            <hr style="background-color: #f56040;">
            <h5 style="text-align: left; color: #e5c8c2">
                Trainer: {{ trainer.user.first_name }} {{ trainer.user.last_name }}</h5>
            <hr style="background-color: #f56040;">
            <h6 style="text-align: left; color: #e5c8c2">Gender: {{ trainer.gender }}</h6>
            <hr style="background-color: #f56040;">
            <h6 style="text-align: left; color: #e5c8c2">Email: {{ trainer.user.email }}</h6>
            <hr style="background-color: #f56040;">
            <h6 style="text-align: left; color: #e5c8c2">Contact: {{ trainer.phone_number }}</h6>
            <hr style="background-color: #f56040;">
            <h6 style="text-align: left; color: #e5c8c2">Address: {{ trainer.address }}</h6>
            <hr style="background-color: #f56040;">
            <hr style="background-color: #f56040; border: 2px solid #f56040">
            <hr style="background-color: #f56040; border: 2px solid #f56040">
            <button
                    type="submit"
                    class="submit"><a href="{% url 'App_main:inbox' %}"
                                      style="text-decoration: none; background-color: #f52f05; color: white!important;">Message</a>
            </button>
        </div>
        <div class="col-lg-2"></div>
    </div>
    <hr style="background-color: #f56040; border: 2px solid #f56040">
    <hr>
</div>

<script>
</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
</body>
</html>